title: AMD-Symposium
#author: Author
#email: your-email@example.com
description: A resource of common terms and questions for understanding bioinformatics.

#github_username:  aidewoode
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
